//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AboutResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public AboutResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Resources.AboutResources", typeof(AboutResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحلیلگر: مهندس علی غلامان.
        /// </summary>
        public static string Analyzer {
            get {
                return ResourceManager.GetString("Analyzer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to qholaman_ali65@yahoo.com.
        /// </summary>
        public static string AnalyzerEmail {
            get {
                return ResourceManager.GetString("AnalyzerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3656 981 915 98+.
        /// </summary>
        public static string AnalyzerNumber {
            get {
                return ResourceManager.GetString("AnalyzerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ققنوس، تمامی امتیازات برای پدیدآورندگان محفوظ است..
        /// </summary>
        public static string AppDetails {
            get {
                return ResourceManager.GetString("AppDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستم مدیریت آزمایشگاه‌ها و دارایی‌های ثابت.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طراح و برنامه‌نویس: محمدصادق شاد.
        /// </summary>
        public static string Programmer {
            get {
                return ResourceManager.GetString("Programmer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to m.sadegh.sh@gmail.com.
        /// </summary>
        public static string ProgrammerEmail {
            get {
                return ResourceManager.GetString("ProgrammerEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3224 737 915 98+.
        /// </summary>
        public static string ProgrammerNumber {
            get {
                return ResourceManager.GetString("ProgrammerNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درباره ققنوس.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
