//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class BackupResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public BackupResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Resources.BackupResources", typeof(BackupResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ایجاد فایل پشتیبان وجود ندارد..
        /// </summary>
        public static string BackupCreationFailed {
            get {
                return ResourceManager.GetString("BackupCreationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل پشتیبان با موفقیت در مسیر &quot;{0}&quot; ایجاد شد..
        /// </summary>
        public static string BackupCreationSuceeded {
            get {
                return ResourceManager.GetString("BackupCreationSuceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام فایل پشتیبان.
        /// </summary>
        public static string BackupFileName {
            get {
                return ResourceManager.GetString("BackupFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لطفا یک نام منحصر بفرد برای فایل پشتیبان مشخص کنید..
        /// </summary>
        public static string BackupFileNameDescription {
            get {
                return ResourceManager.GetString("BackupFileNameDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر ایجاد.
        /// </summary>
        public static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبان گیری کنید تا از امنیت اطلاعات خود مطمئن شوید..
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فایل با این نام در مسیر تعیین‌شده وجود دارد. لطفا نام دیگری برای ایجاد فایل پشتیبان انتخاب کنید..
        /// </summary>
        public static string FileExists {
            get {
                return ResourceManager.GetString("FileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آدرس تعیین‌شده یک آدرس نامعتبر است..
        /// </summary>
        public static string InvalidPathAndFileName {
            get {
                return ResourceManager.GetString("InvalidPathAndFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه نامگذاری.
        /// </summary>
        public static string NamingFormat {
            get {
                return ResourceManager.GetString("NamingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شروع.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت تمایل به ایجاد یک نسخه از اطلاعات موجود در بانک اطلاعاتی برنامه و تایید جزئیات ذیل، بر روی دکمه شروع کلیک کنید..
        /// </summary>
        public static string StartDescription {
            get {
                return ResourceManager.GetString("StartDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبان‌گیری.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
