//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MaterialsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public MaterialsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Resources.MaterialsResources", typeof(MaterialsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزایش موجودی.
        /// </summary>
        public static string AddAmount {
            get {
                return ResourceManager.GetString("AddAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متعلق به.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to واحد اندازه‌گیری.
        /// </summary>
        public static string ComputingUnit {
            get {
                return ResourceManager.GetString("ComputingUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد.
        /// </summary>
        public static string ComputingUnitAdad {
            get {
                return ResourceManager.GetString("ComputingUnitAdad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سی سی.
        /// </summary>
        public static string ComputingUnitCc {
            get {
                return ResourceManager.GetString("ComputingUnitCc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string ComputingUnitCount {
            get {
                return ResourceManager.GetString("ComputingUnitCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گرم.
        /// </summary>
        public static string ComputingUnitGram {
            get {
                return ResourceManager.GetString("ComputingUnitGram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کیلوگرم.
        /// </summary>
        public static string ComputingUnitKilogram {
            get {
                return ResourceManager.GetString("ComputingUnitKilogram", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لیتر.
        /// </summary>
        public static string ComputingUnitLiter {
            get {
                return ResourceManager.GetString("ComputingUnitLiter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی انبار.
        /// </summary>
        public static string CurrentAmount {
            get {
                return ResourceManager.GetString("CurrentAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کلیه مواد شیمیایی موجود در انبار همراه با مدیریت موجودی.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرمول‌شیمیایی.
        /// </summary>
        public static string Formula {
            get {
                return ResourceManager.GetString("Formula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزایش موجودی.
        /// </summary>
        public static string IncreaseAmount {
            get {
                return ResourceManager.GetString("IncreaseAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to افزایش موجودی چه میزان است؟.
        /// </summary>
        public static string IncreaseAmountDescription {
            get {
                return ResourceManager.GetString("IncreaseAmountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موجودی اولیه.
        /// </summary>
        public static string InitialAmount {
            get {
                return ResourceManager.GetString("InitialAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت وجود موجودی اولیه برای این ماده‌شیمیایی، مقدار آنرا
        ///وارد کنید..
        /// </summary>
        public static string InitialAmountDescription {
            get {
                return ResourceManager.GetString("InitialAmountDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین ویرایش.
        /// </summary>
        public static string LastModifiedOn {
            get {
                return ResourceManager.GetString("LastModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کمترین مقدار مجاز.
        /// </summary>
        public static string LowestAmount {
            get {
                return ResourceManager.GetString("LowestAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره مواد.
        /// </summary>
        public static string MaterialNo {
            get {
                return ResourceManager.GetString("MaterialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جرم‌ملکولی.
        /// </summary>
        public static string MolecularMass {
            get {
                return ResourceManager.GetString("MolecularMass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to موادی با این نام قبلا ثبت شده‌است..
        /// </summary>
        public static string NameDuplicate {
            get {
                return ResourceManager.GetString("NameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام ماده‌شیمیایی نمی‌تواند خالی باشد..
        /// </summary>
        public static string NameNull {
            get {
                return ResourceManager.GetString("NameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنوز ماده‌شیمیایی ثبت‌نشده است..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در انبار برای ماده {0} حدودا {1} {2} موجودی ثبت شده است.
        ///با حذف {0} تمامی موجودی از انبار حذف خواهد‌شد. آیا از این کار مطمئنید؟.
        /// </summary>
        public static string Referenced {
            get {
                return ResourceManager.GetString("Referenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو براساس نام مواد‌شیمیایی.
        /// </summary>
        public static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماده‌ای با مشخصات مدنظر یافت نشد..
        /// </summary>
        public static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواد‌شیمیایی.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعلوم.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
    }
}
