//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NotificationsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public NotificationsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Resources.NotificationsResources", typeof(NotificationsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال &quot;{0}&quot; با شماره &quot;{1}&quot; و سریال &quot;{2}&quot; هنوز از امانت برنگشته است..
        /// </summary>
        public static string BorrowedPropMessageFormat {
            get {
                return ResourceManager.GetString("BorrowedPropMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ گارانتی اموال &quot;{0}&quot; با شماره &quot;{1}&quot; و سریال &quot;{2}&quot; به اتمام رسیده است..
        /// </summary>
        public static string ExpiredPropMessageFormat {
            get {
                return ResourceManager.GetString("ExpiredPropMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخفی کن.
        /// </summary>
        public static string Hide {
            get {
                return ResourceManager.GetString("Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متوجه شدم.
        /// </summary>
        public static string IKnow {
            get {
                return ResourceManager.GetString("IKnow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقلام &quot;{0}&quot; با کمبود در انبار رو به رو می‌باشد..
        /// </summary>
        public static string ItemMessageFormat {
            get {
                return ResourceManager.GetString("ItemMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواد &quot;{0}&quot; با کمبود در انبار رو به رو می‌باشد..
        /// </summary>
        public static string MaterialMessageFormat {
            get {
                return ResourceManager.GetString("MaterialMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان پیام.
        /// </summary>
        public static string MessageTitle {
            get {
                return ResourceManager.GetString("MessageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیامی برای نمایش وجود ندارد..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال &quot;{0}&quot; با شماره &quot;{1}&quot; و سریال &quot;{2}&quot; هنوز از تعمیر برنگشته است..
        /// </summary>
        public static string RepairePropMessageFormat {
            get {
                return ResourceManager.GetString("RepairePropMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نمایش همه.
        /// </summary>
        public static string ShowAll {
            get {
                return ResourceManager.GetString("ShowAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا مایلید تا پیام‌های مخفی به نمایش درآیند؟.
        /// </summary>
        public static string ShowQuestion {
            get {
                return ResourceManager.GetString("ShowQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از این پس پیام‌هایی که قبلا از لیست نمایش مخفی شده‌بودند به نمایش درخواهند آمد..
        /// </summary>
        public static string ShowSucceeded {
            get {
                return ResourceManager.GetString("ShowSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پیام‌ها.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
    }
}
