//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class PropsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public PropsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Resources.PropsResources", typeof(PropsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ثبت.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت کلیه اموال موجود در آزمایشگاه‌ها همراه با سند دهی خودکار برای هر یک.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آزمایشگاه پیشفرض برای تخصیص این اموال کدام است؟.
        /// </summary>
        public static string InitialLabID {
            get {
                return ResourceManager.GetString("InitialLabID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام آزمایشگاه.
        /// </summary>
        public static string LabName {
            get {
                return ResourceManager.GetString("LabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین ویرایش.
        /// </summary>
        public static string LastModifiedOn {
            get {
                return ResourceManager.GetString("LastModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اموال نمی تواند خالی باشد..
        /// </summary>
        public static string NameNull {
            get {
                return ResourceManager.GetString("NameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموالی در انبار ثبت نشده‌است..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره پلاک.
        /// </summary>
        public static string PlaqueNo {
            get {
                return ResourceManager.GetString("PlaqueNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره اموال.
        /// </summary>
        public static string PropNo {
            get {
                return ResourceManager.GetString("PropNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموالی با این شناسه قبلا ثبت شده‌است..
        /// </summary>
        public static string PropNoDuplicate {
            get {
                return ResourceManager.GetString("PropNoDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه اموال باید مقدار صحیح داشته‌باشد..
        /// </summary>
        public static string PropNoInvalid {
            get {
                return ResourceManager.GetString("PropNoInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شناسه اموال نمی‌تواند خالی باشد..
        /// </summary>
        public static string PropNoNull {
            get {
                return ResourceManager.GetString("PropNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ خرید.
        /// </summary>
        public static string PurchasingDate {
            get {
                return ResourceManager.GetString("PurchasingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ خرید نامعتبر است..
        /// </summary>
        public static string PurchasingDateInvalid {
            get {
                return ResourceManager.GetString("PurchasingDateInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} با شماره اموال {1} قبل از حذف می بایست از لیست اموال آزمایشگاه {2} حذف شود. آیا مطمئنید؟.
        /// </summary>
        public static string Referenced {
            get {
                return ResourceManager.GetString("Referenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو براساس نام‌ اموال.
        /// </summary>
        public static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموالی با مشخصات مدنظر یافت نشد..
        /// </summary>
        public static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سریال.
        /// </summary>
        public static string SerialNo {
            get {
                return ResourceManager.GetString("SerialNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموالی با این شماره سریال قبلا ثبت شده‌است..
        /// </summary>
        public static string SerialNoDuplicate {
            get {
                return ResourceManager.GetString("SerialNoDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to شماره سریال اموال نمی‌تواند خالی باشد..
        /// </summary>
        public static string SerialNoNull {
            get {
                return ResourceManager.GetString("SerialNoNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ گارانتی.
        /// </summary>
        public static string WarrantyExpirationDate {
            get {
                return ResourceManager.GetString("WarrantyExpirationDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ گارانتی نامعتبر است..
        /// </summary>
        public static string WarrantyExpirationDateInvalid {
            get {
                return ResourceManager.GetString("WarrantyExpirationDateInvalid", resourceCulture);
            }
        }
    }
}
