//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RepositoryMaterialsAndItemsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public RepositoryMaterialsAndItemsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Resources.RepositoryMaterialsAndItemsResources", typeof(RepositoryMaterialsAndItemsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع عملیات.
        /// </summary>
        public static string ActionType {
            get {
                return ResourceManager.GetString("ActionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to همه.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار.
        /// </summary>
        public static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان به {0}.
        /// </summary>
        public static string AmountBy {
            get {
                return ResourceManager.GetString("AmountBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مقدار/تعداد.
        /// </summary>
        public static string AmountCount {
            get {
                return ResourceManager.GetString("AmountCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to میزان.
        /// </summary>
        public static string AmountDefault {
            get {
                return ResourceManager.GetString("AmountDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعداد.
        /// </summary>
        public static string Count {
            get {
                return ResourceManager.GetString("Count", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با خارج‌کردن {0} {1} {2} از انبار، مقدار موجودی به کمتر از میزان تعریف‌شده خواهد رسید.
        ///در صورت نیاز می‌بایست موجودی انبار را برای {2} افزایش دهید. آیا مایل به انجام انتقال هستید؟.
        /// </summary>
        public static string CriticalAmount {
            get {
                return ResourceManager.GetString("CriticalAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to با خارج‌کردن {0} {1} {2} از انبار، تعداد موجودی به کمتر از میزان تعریف‌شده خواهد رسید.
        ///در صورت نیاز می‌بایست موجودی انبار را برای {2} افزایش دهید. آیا مایل به انجام انتقال هستید؟.
        /// </summary>
        public static string CriticalCount {
            get {
                return ResourceManager.GetString("CriticalCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحویل‌دهنده.
        /// </summary>
        public static string DeliverTarget {
            get {
                return ResourceManager.GetString("DeliverTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت مواد شیمیایی و اقلام درخواستی/برگشتی از/به آزمایشگاه‌ها.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت مواد.
        /// </summary>
        public static string EntryMaterial {
            get {
                return ResourceManager.GetString("EntryMaterial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يييي.
        /// </summary>
        public static string EntryMode {
            get {
                return ResourceManager.GetString("EntryMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت سایر اقلام .
        /// </summary>
        public static string EntryOther {
            get {
                return ResourceManager.GetString("EntryOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فیلتر بر اساس.
        /// </summary>
        public static string FilterBy {
            get {
                return ResourceManager.GetString("FilterBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان برداشت از انبار بدلیل موجودی کمتر(حدودا {0} {1}) از میزان خواسته‌شده وجود ندارد..
        /// </summary>
        public static string InvalidAmount {
            get {
                return ResourceManager.GetString("InvalidAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان برداشت از انبار بدلیل موجودی کمتر(حدودا {0} {1}) از میزان خواسته‌شده وجود ندارد..
        /// </summary>
        public static string InvalidCount {
            get {
                return ResourceManager.GetString("InvalidCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام قلم.
        /// </summary>
        public static string ItemName {
            get {
                return ResourceManager.GetString("ItemName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام آزمایشگاه.
        /// </summary>
        public static string LabName {
            get {
                return ResourceManager.GetString("LabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مواد.
        /// </summary>
        public static string MaterialID {
            get {
                return ResourceManager.GetString("MaterialID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مواد.
        /// </summary>
        public static string MaterialName {
            get {
                return ResourceManager.GetString("MaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا به حال اقلامی از انبار خارج نشده است..
        /// </summary>
        public static string NoItemResults {
            get {
                return ResourceManager.GetString("NoItemResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای تخصیص/برگشت ماده‌شیمیایی نام آزمایشگاه ضروریست. آزمایشگاهی برای این منظور ثبت نشده‌است..
        /// </summary>
        public static string NoLabs {
            get {
                return ResourceManager.GetString("NoLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا به حال موادی از انبار خارج نشده است..
        /// </summary>
        public static string NoMaterialResults {
            get {
                return ResourceManager.GetString("NoMaterialResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماده‌شیمیایی در انبار ثبت‌نشده تا امکان تخصیص/برگشت وجود داشته‌باشد..
        /// </summary>
        public static string NoMaterialsAndItems {
            get {
                return ResourceManager.GetString("NoMaterialsAndItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این ماه.
        /// </summary>
        public static string OnlyThisMonth {
            get {
                return ResourceManager.GetString("OnlyThisMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to این هفته.
        /// </summary>
        public static string OnlyThisWeek {
            get {
                return ResourceManager.GetString("OnlyThisWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فقط امروز.
        /// </summary>
        public static string OnlyToday {
            get {
                return ResourceManager.GetString("OnlyToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دیروز و امروز.
        /// </summary>
        public static string OnlyYesterdayAndToday {
            get {
                return ResourceManager.GetString("OnlyYesterdayAndToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحویل‌دهنده/گیرنده.
        /// </summary>
        public static string RegisteredBy {
            get {
                return ResourceManager.GetString("RegisteredBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ تحویل/دریافت.
        /// </summary>
        public static string RegisteredOn {
            get {
                return ResourceManager.GetString("RegisteredOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} درخواستی.
        /// </summary>
        public static string Requested {
            get {
                return ResourceManager.GetString("Requested", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to درخواست از انبار.
        /// </summary>
        public static string RequestFromRepository {
            get {
                return ResourceManager.GetString("RequestFromRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} {1} برگشتی.
        /// </summary>
        public static string Returned {
            get {
                return ResourceManager.GetString("Returned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازگشت به انبار.
        /// </summary>
        public static string ReturnToRepository {
            get {
                return ResourceManager.GetString("ReturnToRepository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فرد تحویل‌گیرنده/دهنده.
        /// </summary>
        public static string TargetApplicant {
            get {
                return ResourceManager.GetString("TargetApplicant", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام {0} نمی‌تواند خالی باشد..
        /// </summary>
        public static string TargetNull {
            get {
                return ResourceManager.GetString("TargetNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواد و اقلام انبار.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحویل‌گیرنده.
        /// </summary>
        public static string Transferee {
            get {
                return ResourceManager.GetString("Transferee", resourceCulture);
            }
        }
    }
}
