//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class RolesResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public RolesResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Resources.RolesResources", typeof(RolesResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدود {0} درصد.
        /// </summary>
        public static string AboutNPercent {
            get {
                return ResourceManager.GetString("AboutNPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدود دسترسی.
        /// </summary>
        public static string AccessibilityPercent {
            get {
                return ResourceManager.GetString("AccessibilityPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه‌ها.
        /// </summary>
        public static string Categories {
            get {
                return ResourceManager.GetString("Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به حذف گروه‌ها باشد..
        /// </summary>
        public static string CategoriesDelete {
            get {
                return ResourceManager.GetString("CategoriesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به مشاهده گروه‌ها باشد..
        /// </summary>
        public static string CategoriesDisplay {
            get {
                return ResourceManager.GetString("CategoriesDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ایجاد گروه جدید باشد..
        /// </summary>
        public static string CategoriesInsert {
            get {
                return ResourceManager.GetString("CategoriesInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در گروه‌ها.
        /// </summary>
        public static string CategoriesSearch {
            get {
                return ResourceManager.GetString("CategoriesSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ویرایش گروه‌ها باشد..
        /// </summary>
        public static string CategoriesUpdate {
            get {
                return ResourceManager.GetString("CategoriesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ ایجاد.
        /// </summary>
        public static string CreatedOn {
            get {
                return ResourceManager.GetString("CreatedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعریف سطوح دسترسی کاربران به بخش‌های مختلف برنامه.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to دسترسی کامل.
        /// </summary>
        public static string FullAccessibility {
            get {
                return ResourceManager.GetString("FullAccessibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقلام.
        /// </summary>
        public static string Items {
            get {
                return ResourceManager.GetString("Items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به حذف اقلام باشد..
        /// </summary>
        public static string ItemsDelete {
            get {
                return ResourceManager.GetString("ItemsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به مشاهده اقلام باشد..
        /// </summary>
        public static string ItemsDisplay {
            get {
                return ResourceManager.GetString("ItemsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ایجاد اقلام جدید باشد..
        /// </summary>
        public static string ItemsInsert {
            get {
                return ResourceManager.GetString("ItemsInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در اقلام.
        /// </summary>
        public static string ItemsSearch {
            get {
                return ResourceManager.GetString("ItemsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ویرایش اقلام باشد..
        /// </summary>
        public static string ItemsUpdate {
            get {
                return ResourceManager.GetString("ItemsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال آزمایشگاه‌ها.
        /// </summary>
        public static string LabProps {
            get {
                return ResourceManager.GetString("LabProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به حذف اموال از آزمایشگاه‌ها باشد..
        /// </summary>
        public static string LabPropsDelete {
            get {
                return ResourceManager.GetString("LabPropsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به مشاهده اموال اختصاص یافته به آزمایشگاه‌ها باشد..
        /// </summary>
        public static string LabPropsDisplay {
            get {
                return ResourceManager.GetString("LabPropsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به اختصاص اموال به آزمایشگاه‌ها باشد..
        /// </summary>
        public static string LabPropsInsert {
            get {
                return ResourceManager.GetString("LabPropsInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در اموال آزمایشگاه‌ها.
        /// </summary>
        public static string LabPropsSearch {
            get {
                return ResourceManager.GetString("LabPropsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آزمایشگاه‌ها.
        /// </summary>
        public static string Labs {
            get {
                return ResourceManager.GetString("Labs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به حذف آزمایشگاه باشد..
        /// </summary>
        public static string LabsDelete {
            get {
                return ResourceManager.GetString("LabsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به مشاهده آزمایشگاه باشد..
        /// </summary>
        public static string LabsDisplay {
            get {
                return ResourceManager.GetString("LabsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ایجاد آزمایشگاه جدید باشد..
        /// </summary>
        public static string LabsInsert {
            get {
                return ResourceManager.GetString("LabsInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در آزمایشگاه‌ها.
        /// </summary>
        public static string LabsSearch {
            get {
                return ResourceManager.GetString("LabsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ویرایش آزمایشگاه باشد..
        /// </summary>
        public static string LabsUpdate {
            get {
                return ResourceManager.GetString("LabsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ آخرین ویرایش.
        /// </summary>
        public static string LastModifiedOn {
            get {
                return ResourceManager.GetString("LastModifiedOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رخداد‌ها.
        /// </summary>
        public static string Logs {
            get {
                return ResourceManager.GetString("Logs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به حذف رخدادها باشد..
        /// </summary>
        public static string LogsDelete {
            get {
                return ResourceManager.GetString("LogsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به مشاهده رخدادها باشد..
        /// </summary>
        public static string LogsDisplay {
            get {
                return ResourceManager.GetString("LogsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در رخدادها.
        /// </summary>
        public static string LogsSearch {
            get {
                return ResourceManager.GetString("LogsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواد شیمیایی.
        /// </summary>
        public static string Materials {
            get {
                return ResourceManager.GetString("Materials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به حذف مواد شیمیایی باشد..
        /// </summary>
        public static string MaterialsDelete {
            get {
                return ResourceManager.GetString("MaterialsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به مشاهده مواد شیمیایی باشد..
        /// </summary>
        public static string MaterialsDisplay {
            get {
                return ResourceManager.GetString("MaterialsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ایجاد ماده شیمیایی جدید باشد..
        /// </summary>
        public static string MaterialsInsert {
            get {
                return ResourceManager.GetString("MaterialsInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در مواد شیمیایی.
        /// </summary>
        public static string MaterialsSearch {
            get {
                return ResourceManager.GetString("MaterialsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ویرایش مواد شیمیایی باشد..
        /// </summary>
        public static string MaterialsUpdate {
            get {
                return ResourceManager.GetString("MaterialsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشی با این نام قبلا ثبت شده‌است..
        /// </summary>
        public static string NameDuplicate {
            get {
                return ResourceManager.GetString("NameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام نقش نمی تواند خالی باشد..
        /// </summary>
        public static string NameNull {
            get {
                return ResourceManager.GetString("NameNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هنوز سطح دسترسی تعریف نشده است..
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال.
        /// </summary>
        public static string Props {
            get {
                return ResourceManager.GetString("Props", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به حذف اموال‌ها باشد..
        /// </summary>
        public static string PropsDelete {
            get {
                return ResourceManager.GetString("PropsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به مشاهده اموال‌ها باشد..
        /// </summary>
        public static string PropsDisplay {
            get {
                return ResourceManager.GetString("PropsDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ایجاد اموال جدید باشد..
        /// </summary>
        public static string PropsInsert {
            get {
                return ResourceManager.GetString("PropsInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در اموال.
        /// </summary>
        public static string PropsSearch {
            get {
                return ResourceManager.GetString("PropsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت اموال.
        /// </summary>
        public static string PropStatus {
            get {
                return ResourceManager.GetString("PropStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به مشاهده وضعیت اموال باشد..
        /// </summary>
        public static string PropStatusDisplay {
            get {
                return ResourceManager.GetString("PropStatusDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ویرایش وضعیت اموال باشد..
        /// </summary>
        public static string PropStatusUpdate {
            get {
                return ResourceManager.GetString("PropStatusUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ویرایش اموال باشد..
        /// </summary>
        public static string PropsUpdate {
            get {
                return ResourceManager.GetString("PropsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از نقش {0} برای تعیین سطح دسترسی کاربران استفاده شده‌است. ابتدا سطح دسترسی آنها را اصلاح، سپس مبادرت به حذف این نقش نمائید..
        /// </summary>
        public static string Referenced {
            get {
                return ResourceManager.GetString("Referenced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در اختصاص/برگشت اقلام.
        /// </summary>
        public static string RepositoryItemsSearch {
            get {
                return ResourceManager.GetString("RepositoryItemsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختصاص/برگشت مواد و اقلام.
        /// </summary>
        public static string RepositoryMaterialsAndItems {
            get {
                return ResourceManager.GetString("RepositoryMaterialsAndItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به حذف سوابق اختصاص/برگشت مواد شیمیایی و اقلام انبار باشد..
        /// </summary>
        public static string RepositoryMaterialsAndItemsDelete {
            get {
                return ResourceManager.GetString("RepositoryMaterialsAndItemsDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به اختصاص/برگشت مواد شیمیایی و اقلام به انبار باشد..
        /// </summary>
        public static string RepositoryMaterialsAndItemsInsert {
            get {
                return ResourceManager.GetString("RepositoryMaterialsAndItemsInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در اختصاص/برگشت مواد شیمیایی.
        /// </summary>
        public static string RepositoryMaterialsSearch {
            get {
                return ResourceManager.GetString("RepositoryMaterialsSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش‌ها.
        /// </summary>
        public static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به حذف نقش‌ها باشد..
        /// </summary>
        public static string RolesDelete {
            get {
                return ResourceManager.GetString("RolesDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به مشاهده نقش‌ها باشد..
        /// </summary>
        public static string RolesDisplay {
            get {
                return ResourceManager.GetString("RolesDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ایجاد نقش جدید باشد..
        /// </summary>
        public static string RolesInsert {
            get {
                return ResourceManager.GetString("RolesInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در نقش‌ها.
        /// </summary>
        public static string RolesSearch {
            get {
                return ResourceManager.GetString("RolesSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ویرایش نقش‌ها باشد..
        /// </summary>
        public static string RolesUpdate {
            get {
                return ResourceManager.GetString("RolesUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو و گزارش‌گیری.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو بر اساس نام نقش.
        /// </summary>
        public static string SearchBy {
            get {
                return ResourceManager.GetString("SearchBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان جستجو، گزارش‌گیری و چاپ را داشته باشد..
        /// </summary>
        public static string SearchDisplay {
            get {
                return ResourceManager.GetString("SearchDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقشی با مشخصات مدنظر یافت نشد..
        /// </summary>
        public static string SearchNoResults {
            get {
                return ResourceManager.GetString("SearchNoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سطوح دسترسی کاربران.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به حذف کاربران باشد..
        /// </summary>
        public static string UsersDelete {
            get {
                return ResourceManager.GetString("UsersDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به مشاهده کاربران باشد..
        /// </summary>
        public static string UsersDisplay {
            get {
                return ResourceManager.GetString("UsersDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ایجاد کاربر جدید باشد..
        /// </summary>
        public static string UsersInsert {
            get {
                return ResourceManager.GetString("UsersInsert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قادر به ویرایش کاربران باشد..
        /// </summary>
        public static string UsersUpdate {
            get {
                return ResourceManager.GetString("UsersUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بدون دسترسی.
        /// </summary>
        public static string ZeroAccessibility {
            get {
                return ResourceManager.GetString("ZeroAccessibility", resourceCulture);
            }
        }
    }
}
