//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SearchResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SearchResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Resources.SearchResources", typeof(SearchResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اختصاص‌دهنده.
        /// </summary>
        public static string AssignedBy {
            get {
                return ResourceManager.GetString("AssignedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس نام گروه.
        /// </summary>
        public static string ByCategoryName {
            get {
                return ResourceManager.GetString("ByCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام گروه.
        /// </summary>
        public static string CategoryName {
            get {
                return ResourceManager.GetString("CategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو چندسطحی پیشرفته به همراه گزارش‌گیری و چاپ.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از مقدار.
        /// </summary>
        public static string FromAmount {
            get {
                return ResourceManager.GetString("FromAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از تاریخ.
        /// </summary>
        public static string FromDate {
            get {
                return ResourceManager.GetString("FromDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از شماره.
        /// </summary>
        public static string FromNo {
            get {
                return ResourceManager.GetString("FromNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to از پلاک.
        /// </summary>
        public static string FromPlaque {
            get {
                return ResourceManager.GetString("FromPlaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در اقلام.
        /// </summary>
        public static string InItems {
            get {
                return ResourceManager.GetString("InItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس کمترین مقدار مجاز.
        /// </summary>
        public static string InItemsByLowestAmount {
            get {
                return ResourceManager.GetString("InItemsByLowestAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to براساس نام اقلام.
        /// </summary>
        public static string InItemsByName {
            get {
                return ResourceManager.GetString("InItemsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس تاریخ ثبت قلم در انبار.
        /// </summary>
        public static string InItemsByRegisterDate {
            get {
                return ResourceManager.GetString("InItemsByRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در اموال اختصاصی آزمایشگاه‌ها.
        /// </summary>
        public static string InLabProps {
            get {
                return ResourceManager.GetString("InLabProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس تاریخ اختصاص.
        /// </summary>
        public static string InLabPropsByAssignDate {
            get {
                return ResourceManager.GetString("InLabPropsByAssignDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس نام آزمایشگاه.
        /// </summary>
        public static string InLabPropsByLabName {
            get {
                return ResourceManager.GetString("InLabPropsByLabName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در آزمایشگاه‌ها.
        /// </summary>
        public static string InLabs {
            get {
                return ResourceManager.GetString("InLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس نام آزمایشگاه.
        /// </summary>
        public static string InLabsByName {
            get {
                return ResourceManager.GetString("InLabsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس پلاک به ثبت رسیده آزمایشگاه‌ها.
        /// </summary>
        public static string InLabsByPlaqueNo {
            get {
                return ResourceManager.GetString("InLabsByPlaqueNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس تاریخ ثبت آزمایشگاه.
        /// </summary>
        public static string InLabsByRegisterDate {
            get {
                return ResourceManager.GetString("InLabsByRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در رخدادهای ثبت‌شده.
        /// </summary>
        public static string InLogs {
            get {
                return ResourceManager.GetString("InLogs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس تاریخ ثبت.
        /// </summary>
        public static string InLogsByLogDate {
            get {
                return ResourceManager.GetString("InLogsByLogDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس نام کاربری.
        /// </summary>
        public static string InLogsByUserName {
            get {
                return ResourceManager.GetString("InLogsByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در مواد شیمیایی.
        /// </summary>
        public static string InMaterials {
            get {
                return ResourceManager.GetString("InMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس کمترین مقدار مجاز.
        /// </summary>
        public static string InMaterialsByLowestAmount {
            get {
                return ResourceManager.GetString("InMaterialsByLowestAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to براساس نام مواد.
        /// </summary>
        public static string InMaterialsByName {
            get {
                return ResourceManager.GetString("InMaterialsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس تاریخ ثبت مواد در انبار.
        /// </summary>
        public static string InMaterialsByRegisterDate {
            get {
                return ResourceManager.GetString("InMaterialsByRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در اموال.
        /// </summary>
        public static string InProps {
            get {
                return ResourceManager.GetString("InProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to براساس نام اموال.
        /// </summary>
        public static string InPropsByName {
            get {
                return ResourceManager.GetString("InPropsByName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس شماره اموال.
        /// </summary>
        public static string InPropsByPropNo {
            get {
                return ResourceManager.GetString("InPropsByPropNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس وضعیت اموال.
        /// </summary>
        public static string InPropsByPropStatus {
            get {
                return ResourceManager.GetString("InPropsByPropStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس تاریخ ثبت اموال در انبار.
        /// </summary>
        public static string InPropsByRegisterDate {
            get {
                return ResourceManager.GetString("InPropsByRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در اقلام اختصاص‌داده شده.
        /// </summary>
        public static string InRepositoryItems {
            get {
                return ResourceManager.GetString("InRepositoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس میزان درخواستی.
        /// </summary>
        public static string InRepositoryItemsByAmount {
            get {
                return ResourceManager.GetString("InRepositoryItemsByAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس تاریخ اختصاص/برگشت.
        /// </summary>
        public static string InRepositoryItemsByRegisterDate {
            get {
                return ResourceManager.GetString("InRepositoryItemsByRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس نام تحویل‌گیرنده/دهنده.
        /// </summary>
        public static string InRepositoryItemsByTarget {
            get {
                return ResourceManager.GetString("InRepositoryItemsByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس نام کاربر.
        /// </summary>
        public static string InRepositoryItemsByUserName {
            get {
                return ResourceManager.GetString("InRepositoryItemsByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو در مواد‌شیمیایی اختصاص‌داده شده.
        /// </summary>
        public static string InRepositoryMaterials {
            get {
                return ResourceManager.GetString("InRepositoryMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس میزان درخواستی.
        /// </summary>
        public static string InRepositoryMaterialsByAmount {
            get {
                return ResourceManager.GetString("InRepositoryMaterialsByAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس تاریخ اختصاص/برگشت.
        /// </summary>
        public static string InRepositoryMaterialsByRegisterDate {
            get {
                return ResourceManager.GetString("InRepositoryMaterialsByRegisterDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس نام تحویل‌گیرنده/دهنده.
        /// </summary>
        public static string InRepositoryMaterialsByTarget {
            get {
                return ResourceManager.GetString("InRepositoryMaterialsByTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بر اساس نام کاربر.
        /// </summary>
        public static string InRepositoryMaterialsByUserName {
            get {
                return ResourceManager.GetString("InRepositoryMaterialsByUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ شروع نامعتبر است..
        /// </summary>
        public static string InValidLowerBoundDate {
            get {
                return ResourceManager.GetString("InValidLowerBoundDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاریخ پایان نامعتبر است..
        /// </summary>
        public static string InValidUpperBoundDate {
            get {
                return ResourceManager.GetString("InValidUpperBoundDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه تعریف شده نامعتبر است..
        /// </summary>
        public static string LowerBoundIsGreaterThanOfUpperBound {
            get {
                return ResourceManager.GetString("LowerBoundIsGreaterThanOfUpperBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام مواد.
        /// </summary>
        public static string MaterialName {
            get {
                return ResourceManager.GetString("MaterialName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خارج از بازه تعریف‌شده.
        /// </summary>
        public static string Outside {
            get {
                return ResourceManager.GetString("Outside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام اموال.
        /// </summary>
        public static string PropName {
            get {
                return ResourceManager.GetString("PropName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت.
        /// </summary>
        public static string PropStatus {
            get {
                return ResourceManager.GetString("PropStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام تحویل‌گیرنده/دهنده.
        /// </summary>
        public static string TargetName {
            get {
                return ResourceManager.GetString("TargetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جستجو.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا مقدار.
        /// </summary>
        public static string ToAmount {
            get {
                return ResourceManager.GetString("ToAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا تاریخ.
        /// </summary>
        public static string ToDate {
            get {
                return ResourceManager.GetString("ToDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا شماره.
        /// </summary>
        public static string ToNo {
            get {
                return ResourceManager.GetString("ToNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تا پلاک.
        /// </summary>
        public static string ToPlaque {
            get {
                return ResourceManager.GetString("ToPlaque", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام کاربری.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
    }
}
