//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SettingsResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Resources.SettingsResources", typeof(SettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پشتیبان‌گیری.
        /// </summary>
        public static string Backup {
            get {
                return ResourceManager.GetString("Backup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نام‌گذاری فایل‌های پشتیبان.
        /// </summary>
        public static string BackupNaming {
            get {
                return ResourceManager.GetString("BackupNaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نحوه و قالب نام‌گذاری فایل‌های پشتیبان را تعیین کنید..
        /// </summary>
        public static string BackupNamingDescription {
            get {
                return ResourceManager.GetString("BackupNamingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر فایل‌های پشتیبان.
        /// </summary>
        public static string BackupPath {
            get {
                return ResourceManager.GetString("BackupPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسیر ایجاد و/یا برگردان فایل‌های پشتیبان اطلاعات برنامه را تعیین کنید..
        /// </summary>
        public static string BackupPathDescription {
            get {
                return ResourceManager.GetString("BackupPathDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آبی (پیشفرض).
        /// </summary>
        public static string BlueDefault {
            get {
                return ResourceManager.GetString("BlueDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییر تنظیمات ققنوس (پیشتیبان‌گیری، زبان، پوسته و...).
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انگلیسی.
        /// </summary>
        public static string ENGB {
            get {
                return ResourceManager.GetString("ENGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فارسی.
        /// </summary>
        public static string FAIR {
            get {
                return ResourceManager.GetString("FAIR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عمومی.
        /// </summary>
        public static string General {
            get {
                return ResourceManager.GetString("General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ایجاد شناسه یکتا (GUID) برای هر فایل.
        /// </summary>
        public static string GenerateGUID {
            get {
                return ResourceManager.GetString("GenerateGUID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گرفتن نام از کاربر.
        /// </summary>
        public static string GetTheNameFromUser {
            get {
                return ResourceManager.GetString("GetTheNameFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سبز.
        /// </summary>
        public static string Green {
            get {
                return ResourceManager.GetString("Green", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زبان مورد استفاده.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حال حاضر زبان‌های محدودی در ققنوس گنجانده شده‌اند. یکی را انتخاب کنید تا نوشتارهای محیط برنامه براساس آن تغییر کنند..
        /// </summary>
        public static string LanguageDescription {
            get {
                return ResourceManager.GetString("LanguageDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در صورت تمایل می توانید ما را در ترجمه برنامه به زبان‌های دیگر یاری نمایید..
        /// </summary>
        public static string LanguageTranslation {
            get {
                return ResourceManager.GetString("LanguageTranslation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} در {1}، {2} بیت، {3} هرتز.
        /// </summary>
        public static string ModesFormat {
            get {
                return ResourceManager.GetString("ModesFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to چاپ.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قرمز.
        /// </summary>
        public static string Red {
            get {
                return ResourceManager.GetString("Red", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پانوشت گزارشات.
        /// </summary>
        public static string ReportsDescription {
            get {
                return ResourceManager.GetString("ReportsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متن مندرج در گزارشات.
        /// </summary>
        public static string ReportsTexts {
            get {
                return ResourceManager.GetString("ReportsTexts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to متون مندرج در بخش‌های مشخص‌شده را هنگام تهیه گزارشات تعیین کنید..
        /// </summary>
        public static string ReportsTextsDescription {
            get {
                return ResourceManager.GetString("ReportsTextsDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان ابتدایی گزارشات.
        /// </summary>
        public static string ReportsTitle {
            get {
                return ResourceManager.GetString("ReportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضوح تصویر.
        /// </summary>
        public static string Resolution {
            get {
                return ResourceManager.GetString("Resolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to برای نمایش بهتر فرم‌های برنامه، می توانید وضوح تصویر را براساس موارد زیر تغییر دهید..
        /// </summary>
        public static string ResolutionDescription {
            get {
                return ResourceManager.GetString("ResolutionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  برای اعمال تغییرات در تنظیمات و مشاهده آن، ققنوس نیاز به راه‌اندازی مجدد دارد. در صورت عدم راه‌اندازی مجدد، تغییرات اعمال‌شده در اجرای بعدی بر روی برنامه اعمال خواهند شد..
        /// </summary>
        public static string RestartRequired {
            get {
                return ResourceManager.GetString("RestartRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات پیشفرض.
        /// </summary>
        public static string RestoreDefaults {
            get {
                return ResourceManager.GetString("RestoreDefaults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوسته.
        /// </summary>
        public static string Theme {
            get {
                return ResourceManager.GetString("Theme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to پوسته رابط کاربری.
        /// </summary>
        public static string ThemeOfUI {
            get {
                return ResourceManager.GetString("ThemeOfUI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رنگ‌بندی مورد استفاده در برنامه را انتخاب کنید..
        /// </summary>
        public static string ThemeOfUIDescription {
            get {
                return ResourceManager.GetString("ThemeOfUIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تنظیمات برنامه.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده از تاریخ و زمان ایجاد فایل‌ها.
        /// </summary>
        public static string UseDateTime {
            get {
                return ResourceManager.GetString("UseDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زرد.
        /// </summary>
        public static string Yellow {
            get {
                return ResourceManager.GetString("Yellow", resourceCulture);
            }
        }
    }
}
