//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.235
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Phoenix.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        public SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Phoenix.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو.
        /// </summary>
        public static string Abort {
            get {
                return ResourceManager.GetString("Abort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اعمال تغییرات.
        /// </summary>
        public static string Apply {
            get {
                return ResourceManager.GetString("Apply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;تعیین توسط سیستم&gt;.
        /// </summary>
        public static string AutoField {
            get {
                return ResourceManager.GetString("AutoField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to انصراف.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لغو تغییرات.
        /// </summary>
        public static string CancelChanges {
            get {
                return ResourceManager.GetString("CancelChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا واقعا قصد خروج از حساب خود را دارید؟.
        /// </summary>
        public static string CloseQuestion {
            get {
                return ResourceManager.GetString("CloseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to روز.
        /// </summary>
        public static string Day {
            get {
                return ResourceManager.GetString("Day", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف همه.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آیا از حذف اطلاعات انتخابی اطمینان دارید؟.
        /// </summary>
        public static string DeleteQuestion {
            get {
                return ResourceManager.GetString("DeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان حذف اطلاعات مورد نظر وجود ندارد..
        /// </summary>
        public static string DeletionFailed {
            get {
                return ResourceManager.GetString("DeletionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت حدف شد..
        /// </summary>
        public static string DeletionSucceeded {
            get {
                return ResourceManager.GetString("DeletionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to در حذف برخی از اطلاعات مشکلی بوجود آمده‌است..
        /// </summary>
        public static string DeletionSucceededWithFailures {
            get {
                return ResourceManager.GetString("DeletionSucceededWithFailures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to توضیحات.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} باید تعیین شود..
        /// </summary>
        public static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to گروه‌ها.
        /// </summary>
        public static string HostTableCategories {
            get {
                return ResourceManager.GetString("HostTableCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقلام.
        /// </summary>
        public static string HostTableItems {
            get {
                return ResourceManager.GetString("HostTableItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال آزمایشگاه ها.
        /// </summary>
        public static string HostTableLabProps {
            get {
                return ResourceManager.GetString("HostTableLabProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to آزمایشگاه ها.
        /// </summary>
        public static string HostTableLabs {
            get {
                return ResourceManager.GetString("HostTableLabs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ورود به حساب کاربری.
        /// </summary>
        public static string HostTableLogin {
            get {
                return ResourceManager.GetString("HostTableLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواد شیمیایی.
        /// </summary>
        public static string HostTableMaterials {
            get {
                return ResourceManager.GetString("HostTableMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اموال.
        /// </summary>
        public static string HostTableProps {
            get {
                return ResourceManager.GetString("HostTableProps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وضعیت اموال.
        /// </summary>
        public static string HostTablePropStatusChanges {
            get {
                return ResourceManager.GetString("HostTablePropStatusChanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اقلام انبار.
        /// </summary>
        public static string HostTableRepositoryItems {
            get {
                return ResourceManager.GetString("HostTableRepositoryItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مواد شیمیایی انبار.
        /// </summary>
        public static string HostTableRepositoryMaterials {
            get {
                return ResourceManager.GetString("HostTableRepositoryMaterials", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نقش‌ها.
        /// </summary>
        public static string HostTableRoles {
            get {
                return ResourceManager.GetString("HostTableRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سیستمی.
        /// </summary>
        public static string HostTableSys {
            get {
                return ResourceManager.GetString("HostTableSys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامعلوم.
        /// </summary>
        public static string HostTableUnknown {
            get {
                return ResourceManager.GetString("HostTableUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربران.
        /// </summary>
        public static string HostTableUsers {
            get {
                return ResourceManager.GetString("HostTableUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صرف‌نظر.
        /// </summary>
        public static string Ignore {
            get {
                return ResourceManager.GetString("Ignore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بازه تعریف شده نامعتبر است..
        /// </summary>
        public static string InvalidBound {
            get {
                return ResourceManager.GetString("InvalidBound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} نامعتبر است..
        /// </summary>
        public static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ماه.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خیر.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تایید.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان انجام عملیات درخواستی وجود ندارد. لطفا مجددا تلاش کنید..
        /// </summary>
        public static string OpFailed {
            get {
                return ResourceManager.GetString("OpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طول {0} باید بین {1} و {2} باشد..
        /// </summary>
        public static string RangeLength {
            get {
                return ResourceManager.GetString("RangeLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} را وارد کنید..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تلاش‌مجدد.
        /// </summary>
        public static string Retry {
            get {
                return ResourceManager.GetString("Retry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسخه {0} - آزمایشی.
        /// </summary>
        public static string ShortVersion {
            get {
                return ResourceManager.GetString("ShortVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان برقراری ارتباط با پایگاه‌داده وجود ندارد.
        ///لطفا اطلاعات مربوطه را اصلاح و سپس اقدام به اجرای دوباره برنامه کنید..
        /// </summary>
        public static string StartUpFailed {
            get {
                return ResourceManager.GetString("StartUpFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to امکان ثبت اطلاعات مورد نظر وجود ندارد..
        /// </summary>
        public static string SubmissionFailed {
            get {
                return ResourceManager.GetString("SubmissionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اطلاعات با موفقیت ثبت شد..
        /// </summary>
        public static string SubmissionSucceeded {
            get {
                return ResourceManager.GetString("SubmissionSucceeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ثبت.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استفاده از اسامی سیستمی مجاز نمی‌باشد..
        /// </summary>
        public static string SystemReserved {
            get {
                return ResourceManager.GetString("SystemReserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string ThreeDot {
            get {
                return ResourceManager.GetString("ThreeDot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to کاربر گرامی، با عرض پوزش مشکلی در اجرای برنامه پیش آمده‌است که امکان ادامه کار را از آن صلب کرده‌است؛ به همین دلیل ما مجبور به بستن برنامه هستیم.
        ///آیا برنامه دوباره راه‌اندازی شود؟.
        /// </summary>
        public static string UnhandledExceptionOccured {
            get {
                return ResourceManager.GetString("UnhandledExceptionOccured", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نامشخص.
        /// </summary>
        public static string Unknown {
            get {
                return ResourceManager.GetString("Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییراتی وجود دارند که هنوز به طور دائمی ثبت نشده‌اند.
        ///آیا باز هم مایل به بستن  پنجره می‌باشید؟.
        /// </summary>
        public static string UnsavedChangesCloseQuestion {
            get {
                return ResourceManager.GetString("UnsavedChangesCloseQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تغییراتی وجود دارند که هنوز به طور دائمی ثبت نشده‌اند.
        ///آیا می‌خواهید تغییرات قبل از هر عملی ثبت شوند؟.
        /// </summary>
        public static string UnsavedChangesSubmitQuestion {
            get {
                return ResourceManager.GetString("UnsavedChangesSubmitQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to سال.
        /// </summary>
        public static string Year {
            get {
                return ResourceManager.GetString("Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بله.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
